// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwS3_zFcUGPYybXcr3XPFBgSyVroN09Hs',
    appId: '1:98785780096:web:ecc4de0fec37c0c0b52165',
    messagingSenderId: '98785780096',
    projectId: 'store-6ee22',
    authDomain: 'store-6ee22.firebaseapp.com',
    storageBucket: 'store-6ee22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIhj8yLiyy9XQWxNqx1wQQiPfZJMxO_io',
    appId: '1:98785780096:android:4044235854e84606b52165',
    messagingSenderId: '98785780096',
    projectId: 'store-6ee22',
    storageBucket: 'store-6ee22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxg3jFB_MrPhpcrBewwqtGGfNSqGGVTwY',
    appId: '1:98785780096:ios:882b92fc1bca465bb52165',
    messagingSenderId: '98785780096',
    projectId: 'store-6ee22',
    storageBucket: 'store-6ee22.appspot.com',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxg3jFB_MrPhpcrBewwqtGGfNSqGGVTwY',
    appId: '1:98785780096:ios:3962dbeb11755f46b52165',
    messagingSenderId: '98785780096',
    projectId: 'store-6ee22',
    storageBucket: 'store-6ee22.appspot.com',
    iosBundleId: 'com.example.store.RunnerTests',
  );
}
